---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: source/_posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: heading
  label: Config
- type: document
  path: _config.yml
  label: Hexo
  match: "**/*"
upload_dir: source/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn server
